<?php

namespace Database\Seeders;

use App\Models\MutualFund;
use Illuminate\Database\Seeder;

class MutualFundSeeder extends Seeder
{
    public function run(): void
    {
        $funds = [
            // Equity Funds
            [
                'name' => 'HDFC Mid-Cap Opportunities Fund',
                'fund_house' => 'HDFC Mutual Fund',
                'category' => 'equity',
                'sub_category' => 'Mid Cap',
                'nav' => 45.67,
                'expense_ratio' => 1.75,
                'one_year_return' => 18.5,
                'three_year_return' => 15.2,
                'five_year_return' => 12.8,
                'ten_year_return' => 14.5,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'Axis Bluechip Fund',
                'fund_house' => 'Axis Mutual Fund',
                'category' => 'equity',
                'sub_category' => 'Large Cap',
                'nav' => 32.45,
                'expense_ratio' => 1.65,
                'one_year_return' => 16.8,
                'three_year_return' => 14.2,
                'five_year_return' => 11.5,
                'ten_year_return' => 13.2,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'SBI Small Cap Fund',
                'fund_house' => 'SBI Mutual Fund',
                'category' => 'equity',
                'sub_category' => 'Small Cap',
                'nav' => 28.90,
                'expense_ratio' => 1.85,
                'one_year_return' => 22.3,
                'three_year_return' => 18.7,
                'five_year_return' => 16.2,
                'ten_year_return' => 17.8,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'ICICI Prudential Technology Fund',
                'fund_house' => 'ICICI Prudential Mutual Fund',
                'category' => 'equity',
                'sub_category' => 'Sectoral',
                'nav' => 65.78,
                'expense_ratio' => 1.95,
                'one_year_return' => 25.6,
                'three_year_return' => 20.3,
                'five_year_return' => 18.7,
                'ten_year_return' => 19.5,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],

            // Debt Funds
            [
                'name' => 'HDFC Liquid Fund',
                'fund_house' => 'HDFC Mutual Fund',
                'category' => 'debt',
                'sub_category' => 'Liquid',
                'nav' => 15.23,
                'expense_ratio' => 0.20,
                'one_year_return' => 6.8,
                'three_year_return' => 6.5,
                'five_year_return' => 6.2,
                'ten_year_return' => 6.8,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'Axis Ultra Short Term Fund',
                'fund_house' => 'Axis Mutual Fund',
                'category' => 'debt',
                'sub_category' => 'Ultra Short Term',
                'nav' => 18.45,
                'expense_ratio' => 0.35,
                'one_year_return' => 7.2,
                'three_year_return' => 6.8,
                'five_year_return' => 6.5,
                'ten_year_return' => 7.0,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'SBI Magnum Gilt Fund',
                'fund_house' => 'SBI Mutual Fund',
                'category' => 'debt',
                'sub_category' => 'Gilt',
                'nav' => 22.67,
                'expense_ratio' => 0.85,
                'one_year_return' => 8.5,
                'three_year_return' => 7.8,
                'five_year_return' => 7.2,
                'ten_year_return' => 7.5,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '3',
                'is_active' => true,
            ],

            // Hybrid Funds
            [
                'name' => 'HDFC Balanced Advantage Fund',
                'fund_house' => 'HDFC Mutual Fund',
                'category' => 'hybrid',
                'sub_category' => 'Balanced Advantage',
                'nav' => 35.89,
                'expense_ratio' => 1.45,
                'one_year_return' => 12.5,
                'three_year_return' => 10.8,
                'five_year_return' => 9.5,
                'ten_year_return' => 10.2,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'ICICI Prudential Equity & Debt Fund',
                'fund_house' => 'ICICI Prudential Mutual Fund',
                'category' => 'hybrid',
                'sub_category' => 'Balanced',
                'nav' => 42.34,
                'expense_ratio' => 1.55,
                'one_year_return' => 13.2,
                'three_year_return' => 11.5,
                'five_year_return' => 10.2,
                'ten_year_return' => 11.0,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'Axis Conservative Hybrid Fund',
                'fund_house' => 'Axis Mutual Fund',
                'category' => 'hybrid',
                'sub_category' => 'Conservative Hybrid',
                'nav' => 28.76,
                'expense_ratio' => 1.25,
                'one_year_return' => 9.8,
                'three_year_return' => 8.5,
                'five_year_return' => 7.8,
                'ten_year_return' => 8.2,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '3',
                'is_active' => true,
            ],

            // Liquid Funds
            [
                'name' => 'SBI Liquid Fund',
                'fund_house' => 'SBI Mutual Fund',
                'category' => 'liquid',
                'sub_category' => 'Liquid',
                'nav' => 12.45,
                'expense_ratio' => 0.15,
                'one_year_return' => 6.2,
                'three_year_return' => 5.8,
                'five_year_return' => 5.5,
                'ten_year_return' => 6.0,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
            [
                'name' => 'ICICI Prudential Liquid Fund',
                'fund_house' => 'ICICI Prudential Mutual Fund',
                'category' => 'liquid',
                'sub_category' => 'Liquid',
                'nav' => 13.67,
                'expense_ratio' => 0.18,
                'one_year_return' => 6.5,
                'three_year_return' => 6.2,
                'five_year_return' => 5.8,
                'ten_year_return' => 6.2,
                'min_investment' => 5000,
                'min_sip' => 500,
                'rating' => '4',
                'is_active' => true,
            ],
        ];

        foreach ($funds as $fund) {
            MutualFund::create($fund);
        }
    }
} 